apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowledge-graph-deployment
  labels:
    app: knowledge-graph
spec:
  selector:
    matchLabels:
      app: knowledge-graph
      role: web
  template:
    metadata:
      labels:
        app: knowledge-graph
        role: web
    spec:
      imagePullSecrets:
      - name: gitlab-registry
      containers:
      - image: registry.gitlab.com/openculinary/knowledge-graph
        imagePullPolicy: IfNotPresent
        name: knowledge-graph
        ports:
        - containerPort: 80
