apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: knowledge-graph-ingress
spec:
  rules:
  - host: knowledge-graph
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: knowledge-graph-service
            port:
              number: 80
